name: ci

on:
    pull_request:
        types: [opened, synchronize, reopened]
    # TODO: デバッグ用なので、developブランチに入れる前に消す
    push:
        branches:
            - feat/ci*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: 17
        - name: use Cache
          uses: actions/cache@v4
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Build with Gradle
          run: ./gradlew build
    lint:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run Lint
          run: ./gradlew lint
        - uses: yutailang0119/action-android-lint@v4
          with:
            report-path: build/reports/*.xml
            ignore-warnings: true
          continue-on-error: false

    # この下の部分でエラーになったので、一時的にコメントアウトしておく
    # ktlint:
    # unit_test:
    # instrumented_test:
