name: ci

on:
    pull_request:
        types: [opened, synchronize, reopened]
    # TODO: デバッグ用なので、developブランチに入れる前に消す
    push:
        branches:
            - feat/ci*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: 17
        - name: use Cache
          uses: actions/cache@v4
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Build with Gradle
          run: ./gradlew build
    lint:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run Lint
          run: ./gradlew lint

    ktlint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run Ktlint
          run: ./gradlew ktlintCheck

    unit_test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run Unit Test
          run: ./gradlew test

    instrumented_unit_test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Enable KVM
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
  
        - name: Run Android Emulator
          uses: ReactiveCircus/android-emulator-runner@v2.33.0
          with:
            api-level: 29
            target: google_apis
            arch: x86_64
            script: ./gradlew connectedCheck